# Generated by Django 4.2.10 on 2024-05-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='В обработке', on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
